// <auto-generated />
namespace VWEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _240520192254 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_240520192254));
        
        string IMigrationMetadata.Id
        {
            get { return "201905250154325_240520192254"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
