// <auto-generated />
namespace VWEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _050620191540 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_050620191540));
        
        string IMigrationMetadata.Id
        {
            get { return "201906051842467_050620191540"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
