// <auto-generated />
namespace VWEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _030620190143 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_030620190143));
        
        string IMigrationMetadata.Id
        {
            get { return "201906030445213_030620190143"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
